// Generated by gencpp from file course_web_dev_ros/ExampleActionFeedback.msg
// DO NOT EDIT!


#ifndef COURSE_WEB_DEV_ROS_MESSAGE_EXAMPLEACTIONFEEDBACK_H
#define COURSE_WEB_DEV_ROS_MESSAGE_EXAMPLEACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace course_web_dev_ros
{
template <class ContainerAllocator>
struct ExampleActionFeedback_
{
  typedef ExampleActionFeedback_<ContainerAllocator> Type;

  ExampleActionFeedback_()
    : progress(0)  {
    }
  ExampleActionFeedback_(const ContainerAllocator& _alloc)
    : progress(0)  {
  (void)_alloc;
    }



   typedef int32_t _progress_type;
  _progress_type progress;





  typedef boost::shared_ptr< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ExampleActionFeedback_

typedef ::course_web_dev_ros::ExampleActionFeedback_<std::allocator<void> > ExampleActionFeedback;

typedef boost::shared_ptr< ::course_web_dev_ros::ExampleActionFeedback > ExampleActionFeedbackPtr;
typedef boost::shared_ptr< ::course_web_dev_ros::ExampleActionFeedback const> ExampleActionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator1> & lhs, const ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress == rhs.progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator1> & lhs, const ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace course_web_dev_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3068c2ff8fa67c9565c90bbf9331baeb";
  }

  static const char* value(const ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3068c2ff8fa67c95ULL;
  static const uint64_t static_value2 = 0x65c90bbf9331baebULL;
};

template<class ContainerAllocator>
struct DataType< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "course_web_dev_ros/ExampleActionFeedback";
  }

  static const char* value(const ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"int32 progress\n"
;
  }

  static const char* value(const ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExampleActionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::course_web_dev_ros::ExampleActionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress: ";
    Printer<int32_t>::stream(s, indent + "  ", v.progress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COURSE_WEB_DEV_ROS_MESSAGE_EXAMPLEACTIONFEEDBACK_H
