// Generated by gencpp from file course_web_dev_ros/ExampleActionResult.msg
// DO NOT EDIT!


#ifndef COURSE_WEB_DEV_ROS_MESSAGE_EXAMPLEACTIONRESULT_H
#define COURSE_WEB_DEV_ROS_MESSAGE_EXAMPLEACTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace course_web_dev_ros
{
template <class ContainerAllocator>
struct ExampleActionResult_
{
  typedef ExampleActionResult_<ContainerAllocator> Type;

  ExampleActionResult_()
    : result(0.0)  {
    }
  ExampleActionResult_(const ContainerAllocator& _alloc)
    : result(0.0)  {
  (void)_alloc;
    }



   typedef float _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> const> ConstPtr;

}; // struct ExampleActionResult_

typedef ::course_web_dev_ros::ExampleActionResult_<std::allocator<void> > ExampleActionResult;

typedef boost::shared_ptr< ::course_web_dev_ros::ExampleActionResult > ExampleActionResultPtr;
typedef boost::shared_ptr< ::course_web_dev_ros::ExampleActionResult const> ExampleActionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator1> & lhs, const ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator1> & lhs, const ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace course_web_dev_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db954e5de3aba73b237d07575e5cac28";
  }

  static const char* value(const ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb954e5de3aba73bULL;
  static const uint64_t static_value2 = 0x237d07575e5cac28ULL;
};

template<class ContainerAllocator>
struct DataType< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "course_web_dev_ros/ExampleActionResult";
  }

  static const char* value(const ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result definition\n"
"float32 result\n"
;
  }

  static const char* value(const ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExampleActionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::course_web_dev_ros::ExampleActionResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<float>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COURSE_WEB_DEV_ROS_MESSAGE_EXAMPLEACTIONRESULT_H
