// Generated by gencpp from file course_web_dev_ros/WaypointActionActionGoal.msg
// DO NOT EDIT!


#ifndef COURSE_WEB_DEV_ROS_MESSAGE_WAYPOINTACTIONACTIONGOAL_H
#define COURSE_WEB_DEV_ROS_MESSAGE_WAYPOINTACTIONACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <course_web_dev_ros/WaypointActionGoal.h>

namespace course_web_dev_ros
{
template <class ContainerAllocator>
struct WaypointActionActionGoal_
{
  typedef WaypointActionActionGoal_<ContainerAllocator> Type;

  WaypointActionActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  WaypointActionActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::course_web_dev_ros::WaypointActionGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointActionActionGoal_

typedef ::course_web_dev_ros::WaypointActionActionGoal_<std::allocator<void> > WaypointActionActionGoal;

typedef boost::shared_ptr< ::course_web_dev_ros::WaypointActionActionGoal > WaypointActionActionGoalPtr;
typedef boost::shared_ptr< ::course_web_dev_ros::WaypointActionActionGoal const> WaypointActionActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator1> & lhs, const ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator1> & lhs, const ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace course_web_dev_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f994f791495bc730e5db0b48612de1d7";
  }

  static const char* value(const ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf994f791495bc730ULL;
  static const uint64_t static_value2 = 0xe5db0b48612de1d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "course_web_dev_ros/WaypointActionActionGoal";
  }

  static const char* value(const ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"WaypointActionGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: course_web_dev_ros/WaypointActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal definition\n"
"geometry_msgs/Point position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointActionActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::course_web_dev_ros::WaypointActionActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::course_web_dev_ros::WaypointActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COURSE_WEB_DEV_ROS_MESSAGE_WAYPOINTACTIONACTIONGOAL_H
