; Auto-generated. Do not edit!


(cl:in-package course_web_dev_ros-msg)


;//! \htmlinclude ExampleActionFeedback.msg.html

(cl:defclass <ExampleActionFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type cl:integer
    :initform 0))
)

(cl:defclass ExampleActionFeedback (<ExampleActionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExampleActionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExampleActionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name course_web_dev_ros-msg:<ExampleActionFeedback> is deprecated: use course_web_dev_ros-msg:ExampleActionFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <ExampleActionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader course_web_dev_ros-msg:progress-val is deprecated.  Use course_web_dev_ros-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExampleActionFeedback>) ostream)
  "Serializes a message object of type '<ExampleActionFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'progress)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExampleActionFeedback>) istream)
  "Deserializes a message object of type '<ExampleActionFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'progress) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExampleActionFeedback>)))
  "Returns string type for a message object of type '<ExampleActionFeedback>"
  "course_web_dev_ros/ExampleActionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExampleActionFeedback)))
  "Returns string type for a message object of type 'ExampleActionFeedback"
  "course_web_dev_ros/ExampleActionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExampleActionFeedback>)))
  "Returns md5sum for a message object of type '<ExampleActionFeedback>"
  "3068c2ff8fa67c9565c90bbf9331baeb")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExampleActionFeedback)))
  "Returns md5sum for a message object of type 'ExampleActionFeedback"
  "3068c2ff8fa67c9565c90bbf9331baeb")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExampleActionFeedback>)))
  "Returns full string definition for message of type '<ExampleActionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%int32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExampleActionFeedback)))
  "Returns full string definition for message of type 'ExampleActionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%int32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExampleActionFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExampleActionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ExampleActionFeedback
    (cl:cons ':progress (progress msg))
))
