; Auto-generated. Do not edit!


(cl:in-package course_web_dev_ros-msg)


;//! \htmlinclude ExampleActionGoal.msg.html

(cl:defclass <ExampleActionGoal> (roslisp-msg-protocol:ros-message)
  ((total
    :reader total
    :initarg :total
    :type cl:float
    :initform 0.0))
)

(cl:defclass ExampleActionGoal (<ExampleActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExampleActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExampleActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name course_web_dev_ros-msg:<ExampleActionGoal> is deprecated: use course_web_dev_ros-msg:ExampleActionGoal instead.")))

(cl:ensure-generic-function 'total-val :lambda-list '(m))
(cl:defmethod total-val ((m <ExampleActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader course_web_dev_ros-msg:total-val is deprecated.  Use course_web_dev_ros-msg:total instead.")
  (total m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExampleActionGoal>) ostream)
  "Serializes a message object of type '<ExampleActionGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'total))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExampleActionGoal>) istream)
  "Deserializes a message object of type '<ExampleActionGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'total) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExampleActionGoal>)))
  "Returns string type for a message object of type '<ExampleActionGoal>"
  "course_web_dev_ros/ExampleActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExampleActionGoal)))
  "Returns string type for a message object of type 'ExampleActionGoal"
  "course_web_dev_ros/ExampleActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExampleActionGoal>)))
  "Returns md5sum for a message object of type '<ExampleActionGoal>"
  "8714f4039a8436108c3414e0ff35edfa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExampleActionGoal)))
  "Returns md5sum for a message object of type 'ExampleActionGoal"
  "8714f4039a8436108c3414e0ff35edfa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExampleActionGoal>)))
  "Returns full string definition for message of type '<ExampleActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%float32 total~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExampleActionGoal)))
  "Returns full string definition for message of type 'ExampleActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%float32 total~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExampleActionGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExampleActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ExampleActionGoal
    (cl:cons ':total (total msg))
))
