; Auto-generated. Do not edit!


(cl:in-package course_web_dev_ros-msg)


;//! \htmlinclude ExampleActionResult.msg.html

(cl:defclass <ExampleActionResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:float
    :initform 0.0))
)

(cl:defclass ExampleActionResult (<ExampleActionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExampleActionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExampleActionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name course_web_dev_ros-msg:<ExampleActionResult> is deprecated: use course_web_dev_ros-msg:ExampleActionResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <ExampleActionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader course_web_dev_ros-msg:result-val is deprecated.  Use course_web_dev_ros-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExampleActionResult>) ostream)
  "Serializes a message object of type '<ExampleActionResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'result))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExampleActionResult>) istream)
  "Deserializes a message object of type '<ExampleActionResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'result) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExampleActionResult>)))
  "Returns string type for a message object of type '<ExampleActionResult>"
  "course_web_dev_ros/ExampleActionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExampleActionResult)))
  "Returns string type for a message object of type 'ExampleActionResult"
  "course_web_dev_ros/ExampleActionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExampleActionResult>)))
  "Returns md5sum for a message object of type '<ExampleActionResult>"
  "db954e5de3aba73b237d07575e5cac28")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExampleActionResult)))
  "Returns md5sum for a message object of type 'ExampleActionResult"
  "db954e5de3aba73b237d07575e5cac28")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExampleActionResult>)))
  "Returns full string definition for message of type '<ExampleActionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%float32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExampleActionResult)))
  "Returns full string definition for message of type 'ExampleActionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%float32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExampleActionResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExampleActionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExampleActionResult
    (cl:cons ':result (result msg))
))
