; Auto-generated. Do not edit!


(cl:in-package course_web_dev_ros-msg)


;//! \htmlinclude WaypointActionFeedback.msg.html

(cl:defclass <WaypointActionFeedback> (roslisp-msg-protocol:ros-message)
  ((position
    :reader position
    :initarg :position
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point))
   (state
    :reader state
    :initarg :state
    :type cl:string
    :initform ""))
)

(cl:defclass WaypointActionFeedback (<WaypointActionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WaypointActionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WaypointActionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name course_web_dev_ros-msg:<WaypointActionFeedback> is deprecated: use course_web_dev_ros-msg:WaypointActionFeedback instead.")))

(cl:ensure-generic-function 'position-val :lambda-list '(m))
(cl:defmethod position-val ((m <WaypointActionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader course_web_dev_ros-msg:position-val is deprecated.  Use course_web_dev_ros-msg:position instead.")
  (position m))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <WaypointActionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader course_web_dev_ros-msg:state-val is deprecated.  Use course_web_dev_ros-msg:state instead.")
  (state m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WaypointActionFeedback>) ostream)
  "Serializes a message object of type '<WaypointActionFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'position) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'state))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'state))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WaypointActionFeedback>) istream)
  "Deserializes a message object of type '<WaypointActionFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'position) istream)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'state) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'state) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WaypointActionFeedback>)))
  "Returns string type for a message object of type '<WaypointActionFeedback>"
  "course_web_dev_ros/WaypointActionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WaypointActionFeedback)))
  "Returns string type for a message object of type 'WaypointActionFeedback"
  "course_web_dev_ros/WaypointActionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WaypointActionFeedback>)))
  "Returns md5sum for a message object of type '<WaypointActionFeedback>"
  "4294e775dffb1318490841da75ade3a4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WaypointActionFeedback)))
  "Returns md5sum for a message object of type 'WaypointActionFeedback"
  "4294e775dffb1318490841da75ade3a4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WaypointActionFeedback>)))
  "Returns full string definition for message of type '<WaypointActionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%geometry_msgs/Point position~%string state~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WaypointActionFeedback)))
  "Returns full string definition for message of type 'WaypointActionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%geometry_msgs/Point position~%string state~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WaypointActionFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'position))
     4 (cl:length (cl:slot-value msg 'state))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WaypointActionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'WaypointActionFeedback
    (cl:cons ':position (position msg))
    (cl:cons ':state (state msg))
))
