; Auto-generated. Do not edit!


(cl:in-package course_web_dev_ros-msg)


;//! \htmlinclude WaypointActionActionGoal.msg.html

(cl:defclass <WaypointActionActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type course_web_dev_ros-msg:WaypointActionGoal
    :initform (cl:make-instance 'course_web_dev_ros-msg:WaypointActionGoal)))
)

(cl:defclass WaypointActionActionGoal (<WaypointActionActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WaypointActionActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WaypointActionActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name course_web_dev_ros-msg:<WaypointActionActionGoal> is deprecated: use course_web_dev_ros-msg:WaypointActionActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <WaypointActionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader course_web_dev_ros-msg:header-val is deprecated.  Use course_web_dev_ros-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <WaypointActionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader course_web_dev_ros-msg:goal_id-val is deprecated.  Use course_web_dev_ros-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <WaypointActionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader course_web_dev_ros-msg:goal-val is deprecated.  Use course_web_dev_ros-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WaypointActionActionGoal>) ostream)
  "Serializes a message object of type '<WaypointActionActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WaypointActionActionGoal>) istream)
  "Deserializes a message object of type '<WaypointActionActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WaypointActionActionGoal>)))
  "Returns string type for a message object of type '<WaypointActionActionGoal>"
  "course_web_dev_ros/WaypointActionActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WaypointActionActionGoal)))
  "Returns string type for a message object of type 'WaypointActionActionGoal"
  "course_web_dev_ros/WaypointActionActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WaypointActionActionGoal>)))
  "Returns md5sum for a message object of type '<WaypointActionActionGoal>"
  "f994f791495bc730e5db0b48612de1d7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WaypointActionActionGoal)))
  "Returns md5sum for a message object of type 'WaypointActionActionGoal"
  "f994f791495bc730e5db0b48612de1d7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WaypointActionActionGoal>)))
  "Returns full string definition for message of type '<WaypointActionActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%WaypointActionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: course_web_dev_ros/WaypointActionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%geometry_msgs/Point position~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WaypointActionActionGoal)))
  "Returns full string definition for message of type 'WaypointActionActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%WaypointActionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: course_web_dev_ros/WaypointActionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%geometry_msgs/Point position~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WaypointActionActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WaypointActionActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'WaypointActionActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
